----------------------------------------
Crashes and bugs
----------------------------------------
{x: 12}.x			| crash
print()				| crash
()				| should return null
[][0]				| crash, should throw an exception (and maybe detect the error before)
{x: 12}.y			| workds, should throw an exception
'x' in {x: 12}			| doesn't work, returns false
|-12|				| lexical analyser
return				| syntaxical error but should work
break				| crash
continue			| crash
'				| workds, but should be a lexical error
"				| idem
'\''				| produces (\) but should be (') 
"\""				| idem
[				| infinite loop
Ã—				| should be like *
Ã·				| should be like /
for 				| infinite loop
let a = 2 a = ""	  | exception, a transforms into a string, and was a integer at declaration
(non-break. space)	  | should be like a classic space
null * 5			| should be null, not act like 0 (confusing)
2 = 5				| should throw semantic exception as 2 is not an l-value
[] = 5				| same but crash in this case
array[]				| returns the last element of the array
{}.size()			| get the number of attrs in object
print(+2)			| crash
'salut'['':'']	  	| must throw a semantic error
12.sqrt()			| crash
Number.sqrt("foo")	  | should throw a semantic error
"salut"()			| crash
12()				| crash
(x -> x)()			| crash
